spring:
  application:
    name: ProgressTracking

  datasource:
    url: jdbc:mysql://localhost:3306/progress_tracking
    username: root
    password: 20amlDqWs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
     mail:
      host: localhost
      port: 1025
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: false

server:
  error:
    include-message: always
    include-binding-errors: always
# MailHog_windows_amd64.exe
